# This is a config for E2B sandbox template.
# You can use 'template_id' (30jvx6jgr1ydkgt57pts) or 'template_name (streamlit-sandbox-me2) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='streamlit-sandbox-me2')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'streamlit-sandbox-me2' })

team_id = "66f03438-ea40-419a-b50f-37834062a46f"
dockerfile = "e2b.Dockerfile"
template_name = "streamlit-sandbox-me2"
template_id = "30jvx6jgr1ydkgt57pts"
