# This is a config for E2B sandbox template.
# You can use template ID (t8lmf01jbiymqo3nttkk) or template name (streamlit-sandbox-s3) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("streamlit-sandbox-s3") # Sync sandbox
# sandbox = await AsyncSandbox.create("streamlit-sandbox-s3") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('streamlit-sandbox-s3')

team_id = "66f03438-ea40-419a-b50f-37834062a46f"
dockerfile = "e2b.Dockerfile"
template_name = "streamlit-sandbox-s3"
template_id = "t8lmf01jbiymqo3nttkk"
