# This is a config for E2B sandbox template.
# You can use 'template_id' (y8cln8sbdr37yfpngsg5) or 'template_name (streamlit-sandbox-me) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='streamlit-sandbox-me')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'streamlit-sandbox-me' })

team_id = "10ac061b-6394-4bee-af80-9d3f3df672e5"
dockerfile = "e2b.Dockerfile"
template_name = "streamlit-sandbox-me"
template_id = "y8cln8sbdr37yfpngsg5"
